import snapshot from "@/data/player-profile-registry.json";
import type { PlayerIdentityRegistry } from "./playerProfiles";

/** Persisted cross-snapshot identity map generated by the refresh pipeline. */
export const PLAYER_PROFILE_REGISTRY = snapshot as PlayerIdentityRegistry;
